use iced::{widget::text_editor, Event};
use std::path::PathBuf;

use crate::app::diff::DiffView;
use crate::app::{AppTheme, CreateTarget, Diagnostic, FileEntry, Language, LogLevel, ViewMode};
use crate::editor::EditorTheme;
use crate::sync::ConflictResolutionMode;
use crate::sync::SyncMessage;
use crate::visual::canvas::CanvasMessage;
use crate::visual::palette::PaletteMessage;
use multicode_core::BlockInfo;

#[derive(Debug, Clone)]
pub enum Message {
    PickFolder,
    FolderPicked(Option<PathBuf>),
    PickFile,
    FilePicked(Option<PathBuf>),
    DefaultEntryPicked(Option<PathBuf>),
    OpenRecent(PathBuf),
    FilesLoaded(Vec<FileEntry>),
    QueryChanged(String),
    SelectFile(PathBuf),
    FileLoaded(Result<(PathBuf, String), String>),
    FileContentEdited(text_editor::Action),
    Undo,
    Redo,
    AnalysisReady(PathBuf, u64, Vec<BlockInfo>, Vec<Diagnostic>),
    SearchTermChanged(String),
    ReplaceTermChanged(String),
    Find,
    FindNext,
    FindPrev,
    Replace,
    ReplaceAll,
    ToggleSearchPanel,
    AutoComplete,
    AutoFormat,
    NewFile,
    SaveFile,
    FileSaved(Result<(), String>),
    NewFileNameChanged(String),
    NewDirectoryNameChanged(String),
    CreateTargetChanged(CreateTarget),
    CreateFile,
    ConfirmCreateFile,
    CancelCreateFile,
    FileCreated(Result<PathBuf, String>),
    CreateDirectory,
    DirectoryCreated(Result<PathBuf, String>),
    RenameFileNameChanged(String),
    RenameFile,
    FileRenamed(Result<PathBuf, String>),
    RequestDeleteFile,
    DeleteFile,
    CancelDeleteFile,
    FileDeleted(Result<PathBuf, String>),
    CloseFile(usize),
    FileClosed(Result<usize, String>),
    ActivateTab(usize),
    StartTabDrag(usize),
    UpdateTabDrag(f32),
    EndTabDrag,
    ReorderTab {
        from: usize,
        to: usize,
    },
    RunSearch,
    SearchFinished(Result<Vec<String>, String>),
    ProjectSearch(String),
    ProjectSearchFinished(Vec<(PathBuf, usize, String)>),
    OpenGotoLine,
    GotoLineInputChanged(String),
    ConfirmGotoLine,
    CancelGotoLine,
    OpenSearchResult(PathBuf, usize),
    RunParse,
    ParseFinished(Result<Vec<String>, String>),
    RunLint,
    LintFinished(Vec<Diagnostic>),
    RunGitBlame(PathBuf),
    RunGitLog,
    GitFinished(Result<Vec<String>, String>),
    RunExport,
    ExportFinished(Result<Vec<String>, String>),
    CoreEvent(String),
    IcedEvent(Event),
    SaveSettings,
    SettingsSaved,
    OpenSettings,
    CloseSettings,
    OpenProjectPicker,
    ToggleDir(PathBuf),
    SearchChanged(String),
    AddFavorite(PathBuf),
    RemoveFavorite(PathBuf),
    ShowContextMenu(PathBuf),
    CloseContextMenu,
    ConfirmDiscard,
    CancelDiscard,
    ThemeSelected(AppTheme),
    SyntectThemeSelected(String),
    LanguageSelected(Language),
    ToggleSearchIndex(bool),
    CacheSizeChanged(String),
    FontSizeChanged(String),
    TabWidthChanged(String),
    ToggleAutoIndent(bool),
    ToggleLineWrapping(bool),
    ToggleHighlightCurrentLine(bool),
    EditorThemeSelected(EditorTheme),
    ToggleLineNumbers(bool),
    ToggleStatusBar(bool),
    ToggleToolbar(bool),
    ToggleMarkdownPreview(bool),
    ConflictResolutionModeSelected(ConflictResolutionMode),
    TogglePreserveMetaFormatting(bool),
    ToggleWatchFiles(bool),
    ToggleMetaPanel,
    ShowMetaDialog,
    CloseMetaDialog,
    MetaTagsChanged(String),
    MetaLinksChanged(String),
    MetaCommentChanged(String),
    SaveMeta,
    StartCaptureShortcut(String),
    SwitchToTextEditor,
    SwitchToVisualEditor,
    ToggleTerminal,
    TerminalCmdChanged(String),
    RunTerminalCmd(String),
    ShowTerminalHelp,
    SaveLog,
    LogLevelSelected(LogLevel),
    OpenDiff(PathBuf, PathBuf, bool),
    OpenGitDiff(PathBuf, String, bool),
    DiffLoaded(Result<DiffView, String>),
    NextDiff,
    PrevDiff,
    ToggleDiffIgnoreWhitespace(bool),
    DiffError(String),
    ClearDiffError,
    ToggleCommandPalette,
    /// Execute a command by its identifier
    ExecuteCommand(String),
    SwitchViewMode(ViewMode),
    FileError(String),
    NavigateUp,
    NavigateDown,
    NavigateInto,
    NavigateBack,
    CanvasEvent(CanvasMessage),
    PaletteEvent(PaletteMessage),
    Sync(SyncMessage),
}
