use iced::{widget::text_editor, Event};
use std::path::PathBuf;

use crate::app::diff::DiffView;
use crate::app::{AppTheme, CreateTarget, FileEntry, HotkeyField, Language};

#[derive(Debug, Clone)]
pub enum Message {
    PickFolder,
    FolderPicked(Option<PathBuf>),
    PickFile,
    FilePicked(Option<PathBuf>),
    OpenRecent(PathBuf),
    FilesLoaded(Vec<FileEntry>),
    QueryChanged(String),
    SelectFile(PathBuf),
    FileLoaded(Result<(PathBuf, String), String>),
    FileContentEdited(text_editor::Action),
    SearchTermChanged(String),
    ReplaceTermChanged(String),
    Find,
    FindNext,
    FindPrev,
    Replace,
    ReplaceAll,
    ToggleSearchPanel,
    AutoComplete,
    AutoFormat,
    SaveFile,
    FileSaved(Result<(), String>),
    NewFileNameChanged(String),
    NewDirectoryNameChanged(String),
    CreateTargetChanged(CreateTarget),
    CreateFile,
    ConfirmCreateFile,
    CancelCreateFile,
    FileCreated(Result<PathBuf, String>),
    CreateDirectory,
    DirectoryCreated(Result<PathBuf, String>),
    RenameFileNameChanged(String),
    RenameFile,
    FileRenamed(Result<PathBuf, String>),
    RequestDeleteFile,
    DeleteFile,
    CancelDeleteFile,
    FileDeleted(Result<PathBuf, String>),
    CloseFile(usize),
    FileClosed(Result<usize, String>),
    ActivateTab(usize),
    ReorderTab { from: usize, to: usize },
    RunSearch,
    SearchFinished(Result<Vec<String>, String>),
    RunParse,
    ParseFinished(Result<Vec<String>, String>),
    RunGitBlame(PathBuf),
    RunGitLog,
    GitFinished(Result<Vec<String>, String>),
    RunExport,
    ExportFinished(Result<Vec<String>, String>),
    CoreEvent(String),
    IcedEvent(Event),
    SaveSettings,
    SettingsSaved,
    OpenSettings,
    CloseSettings,
    ToggleDir(PathBuf),
    ShowContextMenu(PathBuf),
    CloseContextMenu,
    ConfirmDiscard,
    CancelDiscard,
    ThemeSelected(AppTheme),
    SyntectThemeSelected(String),
    LanguageSelected(Language),
    ToggleLineNumbers(bool),
    ToggleStatusBar(bool),
    ToggleToolbar(bool),
    StartCaptureHotkey(HotkeyField),
    SwitchToTextEditor,
    SwitchToVisualEditor,
    ToggleTerminal,
    TerminalCmdChanged(String),
    RunTerminalCmd(String),
    ShowTerminalHelp,
    OpenDiff(PathBuf, PathBuf, bool),
    OpenGitDiff(PathBuf, String, bool),
    DiffLoaded(Result<DiffView, String>),
    NextDiff,
    PrevDiff,
    ToggleDiffIgnoreWhitespace(bool),
    DiffError(String),
    ClearDiffError,
}
